"use client";
import { useState } from "react";
import Link from "next/link";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://sepuente.vercel.app";
const ASSET   = process.env.NEXT_PUBLIC_ASSET_CODE ?? "TMXN";
const ISSUER  = process.env.NEXT_PUBLIC_ISSUER_PUBLIC_KEY ?? "<ISSUER_PUBLIC_KEY>";

const TOML_URL   = `${APP_URL}/.well-known/stellar.toml`;
const DEMO_WALLET = `https://demo-wallet.stellar.org/?home_domain=${encodeURIComponent(APP_URL.replace("https://", ""))}`;
const ANCHOR_CMD  = `npx -p @stellar/anchor-tests stellar-anchor-tests \\\n  --home-domain ${APP_URL.replace("https://", "")} \\\n  --seps 1 10 24 38`;

/* ---------- copy util ---------- */
function useCopy() {
  const [copied, setCopied] = useState<string>("");
  function copy(text: string, key: string) {
    navigator.clipboard.writeText(text).catch(() => {
      const el = document.createElement("textarea");
      el.value = text;
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
    }).finally(() => { setCopied(key); setTimeout(() => setCopied(""), 2000); });
  }
  return { copied, copy };
}

/* ---------- sub-components ---------- */
function CopyBtn({ text, id, copied, copy }: { text: string; id: string; copied: string; copy: (t:string,k:string)=>void }) {
  const ok = copied === id;
  return (
    <button
      onClick={() => copy(text, id)}
      style={{
        background: ok ? "rgba(76,214,142,0.1)" : "rgba(201,162,39,0.08)",
        border: `1px solid ${ok ? "rgba(76,214,142,0.25)" : "rgba(201,162,39,0.2)"}`,
        borderRadius: 6, color: ok ? "#4CD68E" : "#C9A227",
        cursor: "pointer", fontSize: "0.62rem", fontWeight: 700,
        fontFamily: "'JetBrains Mono', monospace", letterSpacing: "0.05em",
        padding: "3px 8px", transition: "all .12s", flexShrink: 0,
      }}
    >{ok ? "✓ OK" : "Copiar"}</button>
  );
}

function CodeBox({ children, id, copied, copy }: { children: string; id: string; copied: string; copy: (t:string,k:string)=>void }) {
  return (
    <div style={{ position:"relative" }}>
      <pre style={{
        background: "rgba(255,255,255,0.025)", border: "1px solid rgba(139,155,181,0.1)",
        borderRadius: 11, padding: "14px 46px 14px 16px", fontSize: "0.75rem",
        overflowX: "auto", color: "#E8E2D5",
        fontFamily: "'JetBrains Mono', monospace", lineHeight: 1.65,
        margin: 0, whiteSpace: "pre-wrap", wordBreak: "break-all",
      }}>{children}</pre>
      <div style={{ position:"absolute", top: 10, right: 10 }}>
        <CopyBtn text={children} id={id} copied={copied} copy={copy} />
      </div>
    </div>
  );
}

const ENDPOINTS = [
  { sep:"SEP-1",   method:"GET",  path:"/.well-known/stellar.toml", note:"CORS abierto" },
  { sep:"SEP-10",  method:"GET",  path:"/auth?account=G...",         note:"Challenge JWT" },
  { sep:"SEP-10",  method:"POST", path:"/auth",                      note:"Verify → JWT" },
  { sep:"SEP-24",  method:"GET",  path:"/sep24/info",                note:"Activos soportados" },
  { sep:"SEP-24",  method:"POST", path:"/sep24/transactions/deposit/interactive",  note:"Inicia depósito" },
  { sep:"SEP-24",  method:"POST", path:"/sep24/transactions/withdraw/interactive", note:"Inicia retiro" },
  { sep:"SEP-24",  method:"GET",  path:"/sep24/transaction?id=<id>", note:"Estado de tx" },
  { sep:"SEP-24",  method:"GET",  path:"/sep24/transactions",        note:"Historial" },
  { sep:"SEP-38",  method:"GET",  path:"/sep38/info",                note:"Pares disponibles" },
  { sep:"SEP-38",  method:"GET",  path:"/sep38/prices",              note:"Precios en tiempo real" },
  { sep:"SEP-38",  method:"POST", path:"/sep38/quote",               note:"Cotización firmada" },
  { sep:"Faucet",  method:"POST", path:"/api/faucet",                note:"Solo testnet" },
];

const ENV_VARS = [
  { k:"NEXT_PUBLIC_APP_URL",          v:"https://sepuente.vercel.app", side:"public" },
  { k:"DRIVER",                        v:"mock | etherfuse",            side:"server" },
  { k:"SIGNING_SECRET_KEY",           v:"Generated by setup-testnet.ts", side:"server" },
  { k:"ISSUER_SECRET_KEY",            v:"Generated by setup-testnet.ts", side:"server" },
  { k:"DISTRIBUTION_SECRET_KEY",      v:"Generated by setup-testnet.ts", side:"server" },
  { k:"JWT_SECRET",                   v:"Random long secret (>=32 chars)", side:"server" },
  { k:"NEXT_PUBLIC_SUPABASE_URL",     v:"https://<id>.supabase.co",   side:"public" },
  { k:"SUPABASE_SERVICE_ROLE_KEY",    v:"Service role key",            side:"server" },
];

const DIFF = [
  { who:"Ramp Kit (SDK)",               desc:"Librería que integra cada app directamente; no expone endpoints SEP propios." },
  { who:"StellarMesh",                  desc:"Mismo patrón SEP-24 pero para saldos de exchanges; no rampas SPEI/bancarias." },
  { who:"Anchor Platform / In a Box",   desc:"Para convertirse en anchor propio; requiere infraestructura y ops." },
  { who:"SEPuente ✓",                   desc:"Adaptador ligero para rampas que ya existen sin modificarlas. Sin custodia.", highlight: true },
];

const SEPS = ["SEP-1","SEP-10","SEP-24","SEP-38"];
const METHOD_COLOR: Record<string, string> = { GET:"rgba(125,186,255,.15)", POST:"rgba(76,214,142,.12)" };
const METHOD_TEXT:  Record<string, string> = { GET:"#7DBAFF", POST:"#4CD68E" };

export default function DevsPage() {
  const { copied, copy } = useCopy();

  return (
    <div style={{ minHeight:"100dvh", background:"#0A1A33", color:"#E8E2D5", fontFamily:"Inter, system-ui, sans-serif" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Syne:wght@700;800&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap');
        *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
        ::-webkit-scrollbar{width:6px;background:#0A1A33}
        ::-webkit-scrollbar-thumb{background:rgba(139,155,181,.2);border-radius:3px}
        a{color:inherit;text-decoration:none}

        /* bg */
        .devs-bg{position:fixed;inset:0;z-index:0;pointer-events:none;overflow:hidden}
        .devs-bg::before{content:'';position:absolute;inset:0;
          background-image:linear-gradient(rgba(139,155,181,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(139,155,181,.035) 1px,transparent 1px);
          background-size:40px 40px;
          mask-image:radial-gradient(ellipse 120% 100% at 50% 0%,black 20%,transparent 70%)}
        .devs-bg::after{content:'';position:absolute;inset:0;
          background:radial-gradient(ellipse 80% 60% at 50% 50%,transparent 40%,rgba(10,26,51,.85) 100%)}
        .blob-d{position:absolute;border-radius:50%;filter:blur(80px)}
        .blob-d1{width:400px;height:300px;top:-100px;left:-80px;
          background:radial-gradient(circle,rgba(201,162,39,.12) 0%,transparent 70%);
          animation:dA 14s ease-in-out infinite}
        .blob-d2{width:350px;height:400px;bottom:-120px;right:-60px;
          background:radial-gradient(circle,rgba(125,186,255,.1) 0%,transparent 70%);
          animation:dB 18s ease-in-out infinite}
        .blob-d3{width:200px;height:200px;top:40%;right:10%;
          background:radial-gradient(circle,rgba(76,214,142,.07) 0%,transparent 70%);
          animation:dC 22s ease-in-out infinite}
        @keyframes dA{0%,100%{transform:translate(0,0)}40%{transform:translate(30px,20px)}70%{transform:translate(-15px,35px)}}
        @keyframes dB{0%,100%{transform:translate(0,0)}35%{transform:translate(-30px,-20px)}65%{transform:translate(15px,-35px)}}
        @keyframes dC{0%,100%{transform:translate(0,0) scale(1)}50%{transform:translate(-20px,15px) scale(1.2)}}

        /* layout */
        .devs-nav{position:sticky;top:0;z-index:10;display:flex;align-items:center;
          justify-content:space-between;padding:14px 24px;
          border-bottom:1px solid rgba(139,155,181,.12);
          background:rgba(10,26,51,.88);backdrop-filter:blur(16px)}
        .devs-brand{display:flex;align-items:center;gap:6px;
          font-family:'Syne',sans-serif;font-size:.95rem;font-weight:800;color:#F5F1E6;
          letter-spacing:-.01em}
        .devs-brand span{color:#C9A227}
        .nav-links{display:flex;align-items:center;gap:6px}
        .nav-link{font-size:.75rem;font-weight:600;color:rgba(139,155,181,.7);
          padding:5px 11px;border-radius:8px;transition:all .12s}
        .nav-link:hover{color:#E8E2D5;background:rgba(255,255,255,.04)}
        .nav-pill{font-size:.62rem;font-family:'JetBrains Mono',monospace;font-weight:700;
          letter-spacing:.07em;text-transform:uppercase;
          background:rgba(201,162,39,.09);border:1px solid rgba(201,162,39,.2);
          color:rgba(201,162,39,.75);padding:3px 9px;border-radius:8px}

        .devs-wrap{position:relative;z-index:1;max-width:840px;margin:0 auto;padding:0 24px 80px}

        /* hero */
        .devs-hero{padding:52px 0 40px;border-bottom:1px solid rgba(139,155,181,.1);margin-bottom:48px}
        .hero-eyebrow{display:flex;align-items:center;gap:8px;margin-bottom:16px}
        .hero-tag{font-size:.65rem;font-family:'JetBrains Mono',monospace;font-weight:700;
          letter-spacing:.09em;text-transform:uppercase;
          background:rgba(201,162,39,.08);border:1px solid rgba(201,162,39,.18);
          color:rgba(201,162,39,.8);padding:4px 10px;border-radius:8px}
        .hero-title{font-family:'Syne',sans-serif;font-size:2.2rem;font-weight:800;
          color:#F5F1E6;letter-spacing:-.04em;line-height:1.1;margin-bottom:12px}
        .hero-title span{color:#C9A227}
        .hero-sub{font-size:.9rem;color:#8B9BB5;line-height:1.65;max-width:520px;margin-bottom:24px}
        .sep-badges{display:flex;gap:8px;flex-wrap:wrap}
        .sep-badge{font-size:.7rem;font-family:'JetBrains Mono',monospace;font-weight:700;
          letter-spacing:.06em;padding:5px 12px;border-radius:8px;
          background:rgba(22,47,89,.8);border:1px solid rgba(139,155,181,.15);color:#8B9BB5;
          cursor:default;transition:all .15s}
        .sep-badge:hover{border-color:rgba(201,162,39,.3);color:#C9A227;background:rgba(201,162,39,.06)}

        /* quick actions */
        .quick-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:48px}
        @media(max-width:640px){.quick-grid{grid-template-columns:1fr}}
        .quick-card{display:flex;flex-direction:column;gap:6px;
          background:rgba(17,40,77,.5);border:1px solid rgba(139,155,181,.1);
          border-radius:13px;padding:16px;transition:all .15s}
        .quick-card:hover{border-color:rgba(201,162,39,.25);background:rgba(17,40,77,.7);transform:translateY(-1px)}
        .qc-icon{width:34px;height:34px;border-radius:9px;display:flex;align-items:center;justify-content:center}
        .qc-title{font-size:.82rem;font-weight:700;color:#F5F1E6}
        .qc-sub{font-size:.72rem;color:#8B9BB5;line-height:1.45}

        /* sections */
        .section{margin-bottom:48px}
        .section-head{display:flex;align-items:center;gap:10px;margin-bottom:20px}
        .section-num{width:26px;height:26px;border-radius:8px;display:flex;align-items:center;justify-content:center;
          font-size:.68rem;font-family:'JetBrains Mono',monospace;font-weight:700;
          background:rgba(201,162,39,.1);border:1px solid rgba(201,162,39,.2);color:#C9A227;flex-shrink:0}
        .section-title{font-family:'Syne',sans-serif;font-size:1.05rem;font-weight:800;color:#F5F1E6;letter-spacing:-.02em}

        /* endpoints table */
        .ep-table{width:100%;border-collapse:collapse}
        .ep-row{border-bottom:1px solid rgba(139,155,181,.07);transition:background .1s}
        .ep-row:hover{background:rgba(255,255,255,.02)}
        .ep-row:last-child{border-bottom:none}
        .ep-sep{padding:10px 12px;font-size:.7rem;font-family:'JetBrains Mono',monospace;font-weight:700;
          letter-spacing:.05em;color:#8B9BB5;white-space:nowrap;vertical-align:middle;width:70px}
        .ep-method{padding:10px 8px;width:52px;vertical-align:middle}
        .ep-method span{display:inline-block;font-size:.62rem;font-family:'JetBrains Mono',monospace;
          font-weight:700;letter-spacing:.04em;padding:2px 6px;border-radius:5px}
        .ep-path{padding:10px 8px;font-family:'JetBrains Mono',monospace;font-size:.73rem;
          color:#E8E2D5;vertical-align:middle;word-break:break-all}
        .ep-note{padding:10px 12px;font-size:.72rem;color:#8B9BB5;vertical-align:middle;text-align:right}
        @media(max-width:580px){.ep-note{display:none}.ep-sep{display:none}}

        /* env table */
        .env-table{width:100%;border-collapse:collapse}
        .env-row{border-bottom:1px solid rgba(139,155,181,.07)}
        .env-row:last-child{border-bottom:none}
        .env-key{padding:10px 12px;font-family:'JetBrains Mono',monospace;font-size:.72rem;
          color:#E8E2D5;font-weight:600;vertical-align:top;width:40%}
        .env-val{padding:10px 12px;font-size:.75rem;color:#8B9BB5;vertical-align:top}
        .env-side{padding:10px 8px;vertical-align:top;width:60px}
        .env-side span{display:inline-block;font-size:.6rem;font-family:'JetBrains Mono',monospace;
          font-weight:700;letter-spacing:.05em;padding:2px 6px;border-radius:5px;white-space:nowrap}

        /* card table */
        .diff-list{display:flex;flex-direction:column;gap:10px}
        .diff-card{border-radius:12px;padding:14px 16px;border:1px solid rgba(139,155,181,.1);
          background:rgba(17,40,77,.35);transition:border-color .12s}
        .diff-card.hl{background:rgba(201,162,39,.04);border-color:rgba(201,162,39,.18)}
        .diff-who{font-size:.8rem;font-weight:700;color:#F5F1E6;margin-bottom:3px}
        .diff-card.hl .diff-who{color:#C9A227}
        .diff-desc{font-size:.78rem;color:#8B9BB5;line-height:1.5}

        /* steps */
        .steps-list{display:flex;flex-direction:column;gap:10px}
        .step-row{display:flex;align-items:flex-start;gap:12px;
          padding:14px 16px;border-radius:12px;
          background:rgba(17,40,77,.35);border:1px solid rgba(139,155,181,.08)}
        .step-num{width:26px;height:26px;border-radius:50%;flex-shrink:0;
          display:flex;align-items:center;justify-content:center;
          font-size:.7rem;font-weight:700;font-family:'JetBrains Mono',monospace;
          background:rgba(76,214,142,.1);border:1px solid rgba(76,214,142,.25);color:#4CD68E;margin-top:1px}
        .step-body{}
        .step-title{font-size:.82rem;font-weight:700;color:#F5F1E6;margin-bottom:3px}
        .step-desc{font-size:.76rem;color:#8B9BB5;line-height:1.5}
        .step-code{display:inline-block;font-family:'JetBrains Mono',monospace;font-size:.72rem;
          background:rgba(22,47,89,.8);border:1px solid rgba(139,155,181,.1);
          border-radius:6px;padding:1px 7px;color:#E8E2D5}

        /* notice */
        .notice{display:flex;align-items:flex-start;gap:10px;
          padding:14px 16px;border-radius:11px;
          background:rgba(201,162,39,.05);border:1px solid rgba(201,162,39,.15);
          font-size:.78rem;color:#8B9BB5;line-height:1.5;margin-top:16px}
        .notice-icon{flex-shrink:0;margin-top:1px;color:#C9A227}

        .inline-link{color:#C9A227;text-decoration:underline;text-decoration-color:rgba(201,162,39,.3)}
        .inline-link:hover{text-decoration-color:#C9A227}

        table{position:relative;z-index:1;border-radius:12px;overflow:hidden;
          background:rgba(17,40,77,.4);border:1px solid rgba(139,155,181,.1)}
      `}</style>

      {/* 3D Background */}
      <div className="devs-bg">
        <div className="blob-d blob-d1"/>
        <div className="blob-d blob-d2"/>
        <div className="blob-d blob-d3"/>
      </div>

      {/* Nav */}
      <nav className="devs-nav">
        <Link href="/" className="devs-brand">
          <span>⟴</span> SEPuente
        </Link>
        <div className="nav-links">
          <span className="nav-pill">Docs</span>
          <a href="https://github.com/ALFA117/sepuente" target="_blank" rel="noreferrer" className="nav-link">GitHub ↗</a>
          <Link href="/demo" className="nav-link">Demo →</Link>
        </div>
      </nav>

      <div className="devs-wrap">

        {/* Hero */}
        <div className="devs-hero">
          <div className="hero-eyebrow">
            <span className="hero-tag">Documentación técnica</span>
          </div>
          <h1 className="hero-title">
            Integra rampas MXN<br/>en <span>Stellar</span> hoy mismo
          </h1>
          <p className="hero-sub">
            Gateway open source y no custodial que implementa el stack SEP completo.
            Apunta tu wallet o app al dominio — listo.
          </p>
          <div className="sep-badges">
            {SEPS.map(s => <span key={s} className="sep-badge">{s}</span>)}
            <span className="sep-badge">CORS abierto</span>
            <span className="sep-badge">No custodial</span>
            <span className="sep-badge">Open source</span>
          </div>
        </div>

        {/* Quick actions */}
        <div className="quick-grid">
          <a href={DEMO_WALLET} target="_blank" rel="noreferrer" className="quick-card">
            <div className="qc-icon" style={{background:"rgba(76,214,142,.1)",color:"#4CD68E"}}>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>
            </div>
            <div className="qc-title">Demo Wallet SDF ↗</div>
            <div className="qc-sub">Prueba el flujo completo sin código en la wallet de Stellar.</div>
          </a>
          <a href={TOML_URL} target="_blank" rel="noreferrer" className="quick-card">
            <div className="qc-icon" style={{background:"rgba(201,162,39,.1)",color:"#C9A227"}}>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>
            </div>
            <div className="qc-title">stellar.toml ↗</div>
            <div className="qc-sub">Manifiesto de descubrimiento con todos los endpoints.</div>
          </a>
          <Link href="/" className="quick-card">
            <div className="qc-icon" style={{background:"rgba(125,186,255,.1)",color:"#7DBAFF"}}>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>
            </div>
            <div className="qc-title">Demo interactivo</div>
            <div className="qc-sub">Flujo de depósito y retiro en vivo sobre testnet.</div>
          </Link>
        </div>

        {/* 1. Endpoints */}
        <div className="section">
          <div className="section-head">
            <div className="section-num">01</div>
            <div className="section-title">Endpoints REST</div>
          </div>
          <table className="ep-table">
            <tbody>
              {ENDPOINTS.map((ep, i) => (
                <tr key={i} className="ep-row">
                  <td className="ep-sep">{ep.sep}</td>
                  <td className="ep-method">
                    <span style={{background:METHOD_COLOR[ep.method]??METHOD_COLOR.GET, color:METHOD_TEXT[ep.method]??METHOD_TEXT.GET}}>
                      {ep.method}
                    </span>
                  </td>
                  <td className="ep-path">{APP_URL}{ep.path}</td>
                  <td className="ep-note">{ep.note}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* 2. Activo */}
        <div className="section">
          <div className="section-head">
            <div className="section-num">02</div>
            <div className="section-title">Activo TMXN</div>
          </div>
          <table className="env-table">
            <tbody>
              {[
                ["Código", ASSET, ""],
                ["Emisor", ISSUER, ""],
                ["Red", "Stellar Testnet", ""],
                ["Colateral", "1 TMXN = 1 MXN simulado (MockDriver)", ""],
              ].map(([k,v], i) => (
                <tr key={i} className="env-row">
                  <td className="env-key">{k}</td>
                  <td className="env-val" style={{fontFamily:"'JetBrains Mono',monospace",fontSize:".71rem"}}>{v}</td>
                  <td className="env-side"></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* 3. stellar.toml */}
        <div className="section">
          <div className="section-head">
            <div className="section-num">03</div>
            <div className="section-title">stellar.toml</div>
          </div>
          <CodeBox id="toml" copied={copied} copy={copy}>{TOML_URL}</CodeBox>
          <div className="notice" style={{marginTop:12}}>
            <div className="notice-icon">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 8v4M12 16h.01"/></svg>
            </div>
            Servido con <code>Content-Type: text/plain</code> y header <code>Access-Control-Allow-Origin: *</code>. CORS completamente abierto en todos los endpoints SEP.
          </div>
        </div>

        {/* 4. Probar en 2 min */}
        <div className="section">
          <div className="section-head">
            <div className="section-num">04</div>
            <div className="section-title">Prueba rápida (sin código)</div>
          </div>
          <div className="steps-list">
            {[
              { title:"Abre Demo Wallet", desc:<>Visita <a href={DEMO_WALLET} target="_blank" rel="noreferrer" className="inline-link">demo-wallet.stellar.org ↗</a> preconfigurado con este anchor.</>},
              { title:"Crea cuenta y fondea", desc:<>Genera un keypair de testnet → "Fund with Friendbot" para obtener XLM.</>},
              { title:"Añade el activo TMXN", desc:<>Add Asset → código <span className="step-code">{ASSET}</span>, emisor <span className="step-code">{ISSUER.slice(0,12)}…</span></>},
              { title:"Conéctate al anchor", desc:<><span className="step-code">{APP_URL.replace("https://","")}</span> en el campo Home Domain.</>},
              { title:"Deposita o retira", desc:"Elige Deposit o Withdraw, sigue el flujo interactivo SEP-24 y comprueba el saldo on-chain."},
            ].map((s, i) => (
              <div key={i} className="step-row">
                <div className="step-num">{i+1}</div>
                <div className="step-body">
                  <div className="step-title">{s.title}</div>
                  <div className="step-desc">{s.desc}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* 5. anchor-tests */}
        <div className="section">
          <div className="section-head">
            <div className="section-num">05</div>
            <div className="section-title">Suite de tests (CI)</div>
          </div>
          <CodeBox id="anchortest" copied={copied} copy={copy}>{ANCHOR_CMD}</CodeBox>
          <div className="notice">
            <div className="notice-icon">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 8v4M12 16h.01"/></svg>
            </div>
            Requiere Node 18+ y variable <code>DRIVER=mock</code>. Corre SEPs 1, 10, 24 y 38. Todos los tests pasan en sandbox.
          </div>
        </div>

        {/* 6. Conectar wallet */}
        <div className="section">
          <div className="section-head">
            <div className="section-num">06</div>
            <div className="section-title">Conectar tu wallet</div>
          </div>
          <p style={{fontSize:".82rem",color:"#8B9BB5",marginBottom:12,lineHeight:1.6}}>
            Apunta el campo <code style={{fontFamily:"JetBrains Mono,monospace",background:"rgba(22,47,89,.8)",padding:"1px 6px",borderRadius:5,fontSize:".74rem"}}>home_domain</code> de tu wallet a:
          </p>
          <CodeBox id="homedomain" copied={copied} copy={copy}>{APP_URL.replace("https://","")}</CodeBox>
          <p style={{fontSize:".8rem",color:"#8B9BB5",marginTop:12,lineHeight:1.65}}>
            La wallet leerá el <code style={{fontFamily:"JetBrains Mono,monospace",fontSize:".73rem"}}>stellar.toml</code>, descubrirá los endpoints SEP-10 y SEP-24 automáticamente, y podrá ofrecer depósito y retiro de pesos MXN sin ninguna integración adicional.
          </p>
        </div>

        {/* 7. ENV vars */}
        <div className="section">
          <div className="section-head">
            <div className="section-num">07</div>
            <div className="section-title">Variables de entorno</div>
          </div>
          <table className="env-table">
            <tbody>
              {ENV_VARS.map((e, i) => (
                <tr key={i} className="env-row">
                  <td className="env-key">{e.k}</td>
                  <td className="env-val">{e.v}</td>
                  <td className="env-side">
                    <span style={{
                      background: e.side==="server" ? "rgba(224,82,82,.1)" : "rgba(76,214,142,.1)",
                      color: e.side==="server" ? "#E05252" : "#4CD68E",
                    }}>{e.side==="server" ? "server" : "public"}</span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="notice">
            <div className="notice-icon" style={{color:"#E05252"}}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
            </div>
            Las variables marcadas <code>server</code> (llaves de firma, JWT_SECRET, service role) nunca se exponen al navegador. Solo las <code>NEXT_PUBLIC_*</code> son accesibles en el cliente.
          </div>
        </div>

        {/* 8. Diferenciación */}
        <div className="section">
          <div className="section-head">
            <div className="section-num">08</div>
            <div className="section-title">¿Por qué SEPuente?</div>
          </div>
          <div className="diff-list">
            {DIFF.map((d, i) => (
              <div key={i} className={`diff-card${d.highlight?" hl":""}`}>
                <div className="diff-who">{d.who}</div>
                <div className="diff-desc">{d.desc}</div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
}
